/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module exp_comp(a, b, eq, gt, lt);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  input [3:0] a;
  input [3:0] b;
  output eq;
  output gt;
  output lt;
  sky130_fd_sc_hd__clkinv_1 _36_ (
    .A(_16_),
    .Y(_24_)
  );
  sky130_fd_sc_hd__clkinv_1 _37_ (
    .A(_15_),
    .Y(_25_)
  );
  sky130_fd_sc_hd__nand2b_1 _38_ (
    .A_N(_19_),
    .B(_15_),
    .Y(_26_)
  );
  sky130_fd_sc_hd__o21ai_0 _39_ (
    .A1(_24_),
    .A2(_20_),
    .B1(_26_),
    .Y(_27_)
  );
  sky130_fd_sc_hd__a22o_1 _40_ (
    .A1(_24_),
    .A2(_20_),
    .B1(_25_),
    .B2(_19_),
    .X(_28_)
  );
  sky130_fd_sc_hd__nand2b_1 _41_ (
    .A_N(_13_),
    .B(_17_),
    .Y(_29_)
  );
  sky130_fd_sc_hd__nand2b_1 _42_ (
    .A_N(_17_),
    .B(_13_),
    .Y(_30_)
  );
  sky130_fd_sc_hd__nor2b_1 _43_ (
    .A(_18_),
    .B_N(_14_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__xnor2_1 _44_ (
    .A(_14_),
    .B(_18_),
    .Y(_32_)
  );
  sky130_fd_sc_hd__nand3_1 _45_ (
    .A(_29_),
    .B(_30_),
    .C(_32_),
    .Y(_33_)
  );
  sky130_fd_sc_hd__nor3_1 _46_ (
    .A(_27_),
    .B(_28_),
    .C(_33_),
    .Y(_21_)
  );
  sky130_fd_sc_hd__a21oi_1 _47_ (
    .A1(_29_),
    .A2(_32_),
    .B1(_31_),
    .Y(_34_)
  );
  sky130_fd_sc_hd__maj3_1 _48_ (
    .A(_24_),
    .B(_20_),
    .C(_26_),
    .X(_35_)
  );
  sky130_fd_sc_hd__o31a_1 _49_ (
    .A1(_27_),
    .A2(_28_),
    .A3(_34_),
    .B1(_35_),
    .X(_23_)
  );
  sky130_fd_sc_hd__nor2_1 _50_ (
    .A(_21_),
    .B(_23_),
    .Y(_22_)
  );
  assign _16_ = a[3];
  assign _20_ = b[3];
  assign _15_ = a[2];
  assign _19_ = b[2];
  assign _14_ = a[1];
  assign _18_ = b[1];
  assign _13_ = a[0];
  assign _17_ = b[0];
  assign eq = _21_;
  assign gt = _22_;
  assign lt = _23_;
endmodule

module float_comp(a, b, aopb);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  input [15:0] a;
  wire [3:0] a_exp;
  wire [10:0] a_man;
  wire a_sgn;
  output [2:0] aopb;
  input [15:0] b;
  wire [3:0] b_exp;
  wire [10:0] b_man;
  wire b_sgn;
  wire exp_eq;
  wire exp_gr;
  wire exp_ls;
  wire man_eq;
  wire man_gr;
  wire man_ls;
  wire sgn_eq;
  wire sgn_gr;
  wire sgn_ls;
  sky130_fd_sc_hd__and2_0 _19_ (
    .A(_16_),
    .B(_09_),
    .X(_15_)
  );
  sky130_fd_sc_hd__a221o_1 _20_ (
    .A1(_16_),
    .A2(_10_),
    .B1(_13_),
    .B2(_15_),
    .C1(_17_),
    .X(_07_)
  );
  sky130_fd_sc_hd__and3_1 _21_ (
    .A(_16_),
    .B(_09_),
    .C(_12_),
    .X(_08_)
  );
  sky130_fd_sc_hd__a221o_1 _22_ (
    .A1(_16_),
    .A2(_11_),
    .B1(_14_),
    .B2(_15_),
    .C1(_18_),
    .X(_06_)
  );
  sign_comp g3 (
    .a(a[15]),
    .b(b[15]),
    .eq(sgn_eq),
    .gt(sgn_gr),
    .lt(sgn_ls)
  );
  exp_comp g4 (
    .a(a[14:11]),
    .b(b[14:11]),
    .eq(exp_eq),
    .gt(exp_gr),
    .lt(exp_ls)
  );
  man_comp g5 (
    .a(a[10:0]),
    .b(b[10:0]),
    .eq(man_eq),
    .gt(man_gr),
    .lt(man_ls)
  );
  assign a_exp = a[14:11];
  assign a_man = a[10:0];
  assign a_sgn = a[15];
  assign b_exp = b[14:11];
  assign b_man = b[10:0];
  assign b_sgn = b[15];
  assign _16_ = sgn_eq;
  assign _10_ = exp_gr;
  assign _17_ = sgn_gr;
  assign _09_ = exp_eq;
  assign _13_ = man_gr;
  assign aopb[1] = _07_;
  assign _12_ = man_eq;
  assign aopb[2] = _08_;
  assign _11_ = exp_ls;
  assign _18_ = sgn_ls;
  assign _14_ = man_ls;
  assign aopb[0] = _06_;
endmodule

module man_comp(a, b, eq, gt, lt);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  input [10:0] a;
  input [10:0] b;
  output eq;
  output gt;
  output lt;
  sky130_fd_sc_hd__clkinv_1 _111_ (
    .A(_057_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__clkinv_1 _112_ (
    .A(_067_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__clkinv_1 _113_ (
    .A(_066_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__clkinv_1 _114_ (
    .A(_054_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__clkinv_1 _115_ (
    .A(_052_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__clkinv_1 _116_ (
    .A(_062_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__clkinv_1 _117_ (
    .A(_058_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nand2b_1 _118_ (
    .A_N(_047_),
    .B(_058_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nand2b_1 _119_ (
    .A_N(_049_),
    .B(_060_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nand2_1 _120_ (
    .A(_051_),
    .B(_077_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nor2b_1 _121_ (
    .A(_048_),
    .B_N(_059_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nor2b_1 _122_ (
    .A(_060_),
    .B_N(_049_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nor2b_1 _123_ (
    .A(_061_),
    .B_N(_050_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__a2111oi_0 _124_ (
    .A1(_051_),
    .A2(_077_),
    .B1(_082_),
    .C1(_083_),
    .D1(_084_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nand3_1 _125_ (
    .A(_079_),
    .B(_080_),
    .C(_085_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _126_ (
    .A1_N(_073_),
    .A2_N(_056_),
    .B1(_068_),
    .B2(_072_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nand2_1 _127_ (
    .A(_072_),
    .B(_068_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__o21ai_0 _128_ (
    .A1(_056_),
    .A2(_073_),
    .B1(_088_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nor2_1 _129_ (
    .A(_087_),
    .B(_089_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nor2_1 _130_ (
    .A(_051_),
    .B(_077_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nor2b_1 _131_ (
    .A(_059_),
    .B_N(_048_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nor2b_1 _132_ (
    .A(_050_),
    .B_N(_061_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__a2111oi_0 _133_ (
    .A1(_047_),
    .A2(_078_),
    .B1(_091_),
    .C1(_092_),
    .D1(_093_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nand2_1 _134_ (
    .A(_090_),
    .B(_094_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nand2b_1 _135_ (
    .A_N(_064_),
    .B(_053_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__o21ai_0 _136_ (
    .A1(_076_),
    .A2(_063_),
    .B1(_096_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nand2b_1 _137_ (
    .A_N(_053_),
    .B(_064_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__xnor2_1 _138_ (
    .A(_052_),
    .B(_063_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nand3_1 _139_ (
    .A(_096_),
    .B(_098_),
    .C(_099_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _140_ (
    .A1_N(_065_),
    .A2_N(_075_),
    .B1(_074_),
    .B2(_055_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nor2_1 _141_ (
    .A(_055_),
    .B(_074_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__a21oi_1 _142_ (
    .A1(_075_),
    .A2(_065_),
    .B1(_102_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nand2_1 _143_ (
    .A(_101_),
    .B(_103_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nor4_1 _144_ (
    .A(_086_),
    .B(_095_),
    .C(_100_),
    .D(_104_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__a211oi_1 _145_ (
    .A1(_079_),
    .A2(_080_),
    .B1(_083_),
    .C1(_084_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__o21ai_0 _146_ (
    .A1(_093_),
    .A2(_105_),
    .B1(_081_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nor2_1 _147_ (
    .A(_091_),
    .B(_100_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__a22oi_1 _148_ (
    .A1(_097_),
    .A2(_098_),
    .B1(_106_),
    .B2(_107_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__o22ai_1 _149_ (
    .A1(_101_),
    .A2(_102_),
    .B1(_104_),
    .B2(_108_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__a221oi_1 _150_ (
    .A1(_087_),
    .A2(_088_),
    .B1(_090_),
    .B2(_109_),
    .C1(_092_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__or2_0 _151_ (
    .A(_082_),
    .B(_110_),
    .X(_071_)
  );
  sky130_fd_sc_hd__nor3_1 _152_ (
    .A(_082_),
    .B(_069_),
    .C(_110_),
    .Y(_070_)
  );
  assign _048_ = a[10];
  assign _059_ = b[10];
  assign _057_ = a[9];
  assign _068_ = b[9];
  assign _056_ = a[8];
  assign _067_ = b[8];
  assign _055_ = a[7];
  assign _066_ = b[7];
  assign _054_ = a[6];
  assign _065_ = b[6];
  assign _053_ = a[5];
  assign _064_ = b[5];
  assign _052_ = a[4];
  assign _063_ = b[4];
  assign _051_ = a[3];
  assign _062_ = b[3];
  assign _050_ = a[2];
  assign _061_ = b[2];
  assign _049_ = a[1];
  assign _060_ = b[1];
  assign _047_ = a[0];
  assign _058_ = b[0];
  assign eq = _069_;
  assign gt = _070_;
  assign lt = _071_;
endmodule

module sign_comp(a, b, eq, gt, lt);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  input a;
  input b;
  output eq;
  output gt;
  output lt;
  sky130_fd_sc_hd__nor2b_1 _5_ (
    .A(_0_),
    .B_N(_1_),
    .Y(_3_)
  );
  sky130_fd_sc_hd__nor2b_1 _6_ (
    .A(_1_),
    .B_N(_0_),
    .Y(_4_)
  );
  sky130_fd_sc_hd__xnor2_1 _7_ (
    .A(_0_),
    .B(_1_),
    .Y(_2_)
  );
  assign _0_ = a;
  assign _1_ = b;
  assign eq = _2_;
  assign gt = _3_;
  assign lt = _4_;
endmodule
